# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MechtaApp' do

pod 'RestKit', '~> 0.24.0'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'LMDropdownView'

end

